env:
  browser: true

parserOptions:
  ecmaVersion: 2022
  sourceType: module

extends:
  - eslint:recommended
  - plugin:jsdoc/recommended-typescript-flavor-error

ignorePatterns:
  - build

rules:
  no-multiple-empty-lines:
    - error
    - max: 1
  curly:
    - error
    - all
  arrow-parens:
    - error
    - always
  jsdoc/require-jsdoc:
    - error
    - checkConstructors: false
      checkGetters: true
      checkSetters: true
      contexts:
        - ArrowFunctionExpression
        - ClassProperty
        - FunctionDeclaration
        - FunctionExpression
        - MethodDefinition
  jsdoc/valid-types:
    - off
  jsdoc/require-returns-description:
    - off
  jsdoc/require-param-description:
    - off
