env:
  es2021: true
  browser: true

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended

parserOptions:
  ecmaVersion: 2021
  sourceType: module

settings:
  import/resolver:
    alias:
      extensions: ['.js']
      map:
        - ['~', './source/js']