env:
  es2021: true
  browser: true

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended

parserOptions:
  ecmaVersion: 2021
  sourceType: module

settings:
  import/resolver:
    alias:
      extensions: ['.js']
      map:
        - ['~', './src/js']

rules:
  no-multiple-empty-lines:
    - error
    - max: 1
  '@typescript-eslint/explicit-function-return-type':
    - error
  '@typescript-eslint/no-unused-vars':
    - error
  '@typescript-eslint/comma-dangle':
    - error
    - always-multiline
  '@typescript-eslint/object-curly-spacing':
    - error
    - always
  '@typescript-eslint/quotes':
    - error
    - single
