env:
  es2021: true
  browser: true
  jest: true

parserOptions:
  ecmaVersion: 2021
  sourceType: module

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended

plugins:
  - jest-dom

settings:
  import/resolver:
    alias:
      extensions: ['.js']
      map:
        - ['~', './src/js']

rules:
  no-multiple-empty-lines:
    - error
    - max: 1
  curly:
    - error
    - all
  '@typescript-eslint/explicit-function-return-type':
    - error
  '@typescript-eslint/no-explicit-any':
    - error
  '@typescript-eslint/comma-dangle':
    - error
    - always-multiline
  '@typescript-eslint/object-curly-spacing':
    - error
    - always
  '@typescript-eslint/quotes':
    - error
    - single
  '@typescript-eslint/semi':
    - error
    - always
  '@typescript-eslint/no-unused-vars':
    - error
    - vars: all
      args: after-used
      argsIgnorePattern: ^_
      caughtErrors: all
