const ControlType = /** @type {const} */ ({
	BUTTON: 'button',
	CHECKBOX: 'checkbox',
	COLOR: 'color',
	DATE: 'date',
	DATETIME_LOCAL: 'datetime-local',
	EMAIL: 'email',
	FIELDSET: 'fieldset',
	FILE: 'file',
	HIDDEN: 'hidden',
	IMAGE: 'image',
	MONTH: 'month',
	NUMBER: 'number',
	OUTPUT: 'output',
	PASSWORD: 'password',
	RADIO: 'radio',
	RANGE: 'range',
	RESET: 'reset',
	SEARCH: 'search',
	SELECT_MULTIPLE: 'select-multiple',
	SELECT_ONE: 'select-one',
	SUBMIT: 'submit',
	TEL: 'tel',
	TEXT: 'text',
	TEXTAREA: 'textarea',
	TIME: 'time',
	URL: 'url',
	WEEK: 'week',
});

export { ControlType };
