name: Notify

on:
  pull_request:
    # types:
    #   - opened
    #   - reopened

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            *Service*
              ${{ github.repository }}
            *Owner*
              ${{ github.actor }}
            *Owner*
              ${{ github.event_name }}
            *Ref*
              ${{ github.ref }}
            *SHA*
              ${{ github.sha }}
            *Message*
              ${{ env.commitmsg || ➖ }}
            *PR URL*
              [PR URL](https://github.com/${{github.repository}}/pull/${{ github.event.number }})
            *Action URL*
              [ACTION URL](https://github.com/${{github.repository}}/actions/runs/${{ github.run_id }})
