name: Publish

on:
  push:
    branches:
      - production

jobs:
  testing:
    name: Testing
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 14

    steps:
      - name: Install NodeJS v${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'

      - name: Code Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          npm ci

      - name: Build Package
        run: |
          npm run build

      - name: Publish Package
        working-directory: build
        run: |
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
