name: Publish

env:
  NODE_VERSION: 14

on:
  push:
    branches:
      - production

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Install NodeJS v${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: 'https://registry.npmjs.org'

      - name: Code Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          npm ci

      - name: Build Package
        run: |
          npm run build

      - name: Publish Package
        working-directory: build
        run: |
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Send notification
        if: always()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            *Repository* — ${{ github.repository }}
            *Deployment Status* — ${{ job.status }}
